# commit to be tagged for the new release
commit = "HEAD"

project_name = "sbc-rockchip"
github_repo = "siderolabs/sbc-rockchip"
match_deps = "^github.com/(siderolabs/[a-zA-Z0-9-]+)$"

previous = "v0.1.2"
pre_release = false

[notes]

[notes.orangepi]
  title = "OrangePi-5"
  description = """
Add support for OrangePi-5 board.
"""
